#!/usr/bin/env node
/**
 * Postinstall: ensure harness global directories exist.
 * Auto-generated by flow-install.
 */
import fs from "node:fs/promises";
import os from "node:os";
import path from "node:path";

const home = os.homedir();
await fs.mkdir(path.join(home, ".agents", "skills"), { recursive: true }).catch(() => {});
await fs.mkdir(path.join(home, ".agents", "claude-marketplace", ".claude-plugin"), { recursive: true }).catch(() => {});
await fs.mkdir(path.join(home, ".claude", "skills"), { recursive: true }).catch(() => {});
