#!/usr/bin/env node
/**
 * Validate project-local skills in .agents/skills/.
 * Auto-generated by flow-install.
 */
import fs from "node:fs/promises";
import path from "node:path";

const projectRoot = process.cwd();
const DEFAULT_INSTALL_PATHS = {
  agentsFile: "AGENTS.md",
  contextDir: ".jarvis/context",
  skillsDir: ".agents/skills",
  scriptsDir: "scripts/flow",
};
const required = ["name","type","version","owner","status","blast_radius","description","permissions","data_categories","egress","invoke","location"];
const readJsonSafe = async (p) => { try { return JSON.parse(await fs.readFile(p, "utf8")); } catch { return null; } };
const resolveInstallPaths = async () => {
  const lockfile = await readJsonSafe(path.join(projectRoot, "flow-install.lock.json"));
  return { ...DEFAULT_INSTALL_PATHS, ...(lockfile?.installPaths || {}) };
};

const run = async () => {
  const installPaths = await resolveInstallPaths();
  const skillsRoot = path.resolve(projectRoot, installPaths.skillsDir);
  const errors = [];
  let entries;
  try { entries = await fs.readdir(skillsRoot, { withFileTypes: true }); } catch { console.log("No project-local skills found at " + skillsRoot + "."); return; }
  for (const entry of entries) {
    if (!entry.isDirectory()) continue;
    const mPath = path.join(skillsRoot, entry.name, "manifest.yaml");
    let content; try { content = await fs.readFile(mPath, "utf8"); } catch { errors.push("Missing manifest.yaml in " + entry.name); continue; }
    const data = {};
    for (const line of content.split("\n")) {
      const i = line.indexOf(":"); if (i === -1) continue;
      data[line.slice(0, i).trim()] = line.slice(i + 1).trim();
    }
    for (const f of required) { if (!data[f]) errors.push(entry.name + ": missing " + f); }
  }
  if (errors.length) { console.error("Validation failed:\n" + errors.map(e => "- " + e).join("\n")); process.exitCode = 1; }
  else console.log("Skill validation passed.");
};

run().catch((e) => { console.error(e); process.exitCode = 1; });
