#!/usr/bin/env node
/**
 * Verify Flow harness parity for repo, OpenCode, and Claude Code.
 * Auto-generated by flow-install.
 */
import fs from "node:fs/promises";
import os from "node:os";
import path from "node:path";

const projectRoot = process.cwd();
const home = os.homedir();
const GLOBAL_SKILLS_DIR = path.join(home, ".agents", "skills");
const GLOBAL_CLAUDE_SKILLS_DIR = path.join(home, ".claude", "skills");
const GLOBAL_COMMUNITY_METADATA = path.join(home, ".agents", "community-install.json");
const GLOBAL_CLAUDE_MARKETPLACE = path.join(home, ".agents", "claude-marketplace", ".claude-plugin", "marketplace.json");
const GLOBAL_CLAUDE_SETTINGS = path.join(home, ".claude", "settings.json");
const GLOBAL_OPENCODE_CONFIG = path.join(home, ".config", "opencode", "opencode.json");
const DEFAULT_INSTALL_PATHS = {
  agentsFile: "AGENTS.md",
  contextDir: ".jarvis/context",
  skillsDir: ".agents/skills",
  scriptsDir: "scripts/flow",
};

const pathExists = async (p) => { try { await fs.access(p); return true; } catch { return false; } };
const readFileSafe = async (p) => { try { return await fs.readFile(p, "utf8"); } catch (e) { if (e.code === "ENOENT") return null; throw e; } };
const readJsonSafe = async (p) => { const raw = await readFileSafe(p); if (!raw) return null; try { return JSON.parse(raw); } catch { return null; } };
const normalizePath = async (candidate) => { try { return await fs.realpath(candidate); } catch { return path.resolve(candidate); } };
const resolveInstallPaths = async () => {
  const lockfile = await readJsonSafe(path.join(projectRoot, "flow-install.lock.json"));
  return { ...DEFAULT_INSTALL_PATHS, ...(lockfile?.installPaths || {}) };
};
const resolveProjectPath = (relativePath) => path.resolve(projectRoot, relativePath);
const checks = [];
const pass = (label, detail = "") => checks.push({ ok: true, label, detail });
const warn = (label, detail = "") => checks.push({ ok: true, level: "WARN", label, detail });
const fail = (label, detail = "") => checks.push({ ok: false, label, detail });

const requirePath = async (label, target) => (await pathExists(target)) ? pass(label, target) : fail(label, target);
const findExecutable = async (name) => {
  const pathEntries = (process.env.PATH || "").split(path.delimiter).filter(Boolean);
  for (const entry of pathEntries) {
    const candidate = path.join(entry, name);
    try {
      await fs.access(candidate, fs.constants.X_OK);
      return candidate;
    } catch {}
  }
  return null;
};

const run = async () => {
  const installPaths = await resolveInstallPaths();
  const agentsPath = resolveProjectPath(installPaths.agentsFile);
  const contextDir = resolveProjectPath(installPaths.contextDir);
  const projectSkillsRoot = resolveProjectPath(installPaths.skillsDir);
  const scriptsDir = resolveProjectPath(installPaths.scriptsDir);
  const expectedContextAgentsRef = installPaths.contextDir.replace(/\\/g, "/") + "/AGENTS.md";
  const expectedRegisterScript = "node " + installPaths.scriptsDir.replace(/\\/g, "/") + "/register-skills.mjs";
  const expectedVerifyScript = "node " + installPaths.scriptsDir.replace(/\\/g, "/") + "/verify-harness.mjs";

  await requirePath("AGENTS.md exists", agentsPath);
  const agents = await readFileSafe(agentsPath);
  if (agents?.includes("<!-- flow:start -->") && agents?.includes("<!-- flow:end -->")) pass("AGENTS.md Flow section present");
  else fail("AGENTS.md Flow section present");

  await requirePath("Context README exists", path.join(contextDir, "README.md"));
  await requirePath("Context AGENTS exists", path.join(contextDir, "AGENTS.md"));
  await requirePath("Memory scopes exist", path.join(contextDir, "scopes", "_scopes.yaml"));
  if (agents?.includes(expectedContextAgentsRef)) pass("AGENTS.md points to context AGENTS", expectedContextAgentsRef);
  else fail("AGENTS.md points to context AGENTS");
  await requirePath("Install lockfile exists", path.join(projectRoot, "flow-install.lock.json"));
  await requirePath("register-skills script exists", path.join(scriptsDir, "register-skills.mjs"));
  await requirePath("validate-skills script exists", path.join(scriptsDir, "validate-skills.mjs"));
  await requirePath("register-claude-skills script exists", path.join(scriptsDir, "register-claude-skills.mjs"));
  await requirePath("verify-harness script exists", path.join(scriptsDir, "verify-harness.mjs"));
  await requirePath("sync-rules script exists", path.join(scriptsDir, "sync-rules.mjs"));

  const jarvisPath = await findExecutable("jarvis");
  if (jarvisPath) pass("jarvis is available in PATH", jarvisPath);
  else fail("jarvis is available in PATH");

  const pkg = await readJsonSafe(path.join(projectRoot, "package.json"));
  if (pkg?.scripts?.["skills:register"] === expectedRegisterScript) pass("package.json skills:register configured", pkg.scripts["skills:register"]);
  else fail("package.json skills:register configured", pkg?.scripts?.["skills:register"] || "missing");
  if (pkg?.scripts?.["harness:verify"] === expectedVerifyScript) pass("package.json harness:verify configured", pkg.scripts["harness:verify"]);
  else fail("package.json harness:verify configured", pkg?.scripts?.["harness:verify"] || "missing");

  await requirePath("Global skills directory exists", GLOBAL_SKILLS_DIR);
  await requirePath("Claude user skills directory exists", GLOBAL_CLAUDE_SKILLS_DIR);

  const opencode = await readJsonSafe(GLOBAL_OPENCODE_CONFIG);
  const opencodePaths = [];
  for (const configuredPath of opencode?.skills?.paths || []) opencodePaths.push(await normalizePath(configuredPath));
  const normalizedGlobal = await normalizePath(GLOBAL_SKILLS_DIR);
  if (opencodePaths.includes(normalizedGlobal)) pass("OpenCode has global skills path", normalizedGlobal);
  else fail("OpenCode has global skills path", normalizedGlobal);
  if (!(await pathExists(projectSkillsRoot))) pass("Project-local skills path optional", projectSkillsRoot);
  else {
    const normalizedProjectSkillsRoot = await normalizePath(projectSkillsRoot);
    if (opencodePaths.includes(normalizedProjectSkillsRoot)) pass("OpenCode has project-local skills path", normalizedProjectSkillsRoot);
    else fail("OpenCode has project-local skills path", normalizedProjectSkillsRoot);
  }

  const claudeSettings = await readJsonSafe(GLOBAL_CLAUDE_SETTINGS);
  const marketplace = await readJsonSafe(GLOBAL_CLAUDE_MARKETPLACE);
  const marketplacePlugins = new Set(Array.isArray(marketplace?.plugins) ? marketplace.plugins.map((plugin) => plugin.name) : []);
  const enabledPlugins = claudeSettings?.enabledPlugins || {};
  if (claudeSettings?.extraKnownMarketplaces?.flow_network?.source?.path) pass("Claude marketplace configured", claudeSettings.extraKnownMarketplaces.flow_network.source.path);
  else fail("Claude marketplace configured");
  if (Array.isArray(marketplace?.plugins) && marketplace.plugins.length > 0) pass("Claude marketplace has plugins", String(marketplace.plugins.length));
  else fail("Claude marketplace has plugins");
  if (marketplacePlugins.has("flow-network")) pass("Claude marketplace contains Flow bundle plugin", "flow-network");
  else fail("Claude marketplace contains Flow bundle plugin", "flow-network");
  if (enabledPlugins["flow-network@flow_network"] === true) pass("Claude enabled Flow bundle plugin", "flow-network@flow_network");
  else fail("Claude enabled Flow bundle plugin", "flow-network@flow_network");

  const localEntries = await fs.readdir(projectSkillsRoot, { withFileTypes: true }).catch(() => []);
  const localSkills = localEntries.filter((entry) => entry.isDirectory()).map((entry) => entry.name);
  const lockfile = await readJsonSafe(path.join(projectRoot, "flow-install.lock.json"));
  const globalCommunityMetadata = await readJsonSafe(GLOBAL_COMMUNITY_METADATA);
  const components = lockfile?.components || {};
  for (const component of ["skills", "claude", "opencode", "scripts", "context", "memory", "agentsMd"]) {
    if (components[component] === true) pass("Lockfile component recorded", component);
    else fail("Lockfile component recorded", component);
  }
  if (lockfile?.contextAgents?.path === expectedContextAgentsRef) pass("Lockfile context AGENTS path recorded", lockfile.contextAgents.path);
  else fail("Lockfile context AGENTS path recorded", lockfile?.contextAgents?.path || "missing");
  if (lockfile?.contextAgents?.version) pass("Lockfile context AGENTS version recorded", lockfile.contextAgents.version);
  else fail("Lockfile context AGENTS version recorded");

  const flowCoreSkills = Array.isArray(lockfile?.flowCoreSkills) ? lockfile.flowCoreSkills : [];
  if (flowCoreSkills.length === 0) {
    warn("Flow core skills inventory unavailable", "No flowCoreSkills recorded in flow-install.lock.json");
  }
  for (const skill of flowCoreSkills) {
    const globalSkillDir = path.join(GLOBAL_SKILLS_DIR, skill);
    const claudeSkillDir = path.join(GLOBAL_CLAUDE_SKILLS_DIR, skill);
    const skillMdPath = path.join(globalSkillDir, "SKILL.md");
    if (await pathExists(globalSkillDir)) pass("Flow core skill installed globally", skill);
    else fail("Flow core skill installed globally", skill);
    if (await pathExists(skillMdPath)) pass("Flow core skill has SKILL.md", skill);
    else fail("Flow core skill has SKILL.md", skill);
    if (opencodePaths.includes(normalizedGlobal) && await pathExists(skillMdPath)) pass("OpenCode can resolve Flow core skill", skill);
    else fail("OpenCode can resolve Flow core skill", skill);
    if (await pathExists(claudeSkillDir)) pass("Claude slash skill installed", skill);
    else fail("Claude slash skill installed", skill);
  }

  const communityConfig = (lockfile?.communitySkills && lockfile.communitySkills.mode !== "none")
    ? { ...(globalCommunityMetadata || {}), ...lockfile.communitySkills }
    : (globalCommunityMetadata || { mode: "none", expected: [], strict: false });
  let expectedCommunitySkills = Array.isArray(communityConfig.expected) ? [...communityConfig.expected] : [];
  if (communityConfig.mode === "full" && expectedCommunitySkills.length === 0 && communityConfig.sourceDir) {
    const communityEntries = await fs.readdir(communityConfig.sourceDir, { withFileTypes: true }).catch(() => []);
    expectedCommunitySkills = communityEntries.filter((entry) => entry.isDirectory()).map((entry) => entry.name).sort();
  }
  if (communityConfig.mode === "none") {
    pass("Community skills not required", "mode=none");
  } else if (communityConfig.mode === "full") {
    if (communityConfig.sourceDir) {
      if (await pathExists(communityConfig.sourceDir)) pass("Community source inventory available", communityConfig.sourceDir);
      else fail("Community source inventory available", communityConfig.sourceDir);
    } else {
      fail("Community source inventory available", "mode=full but sourceDir missing");
    }
    if (expectedCommunitySkills.length > 0) pass("Community expected inventory recorded", String(expectedCommunitySkills.length));
    else fail("Community expected inventory recorded", "mode=full but no expected skills recorded");
    if (typeof communityConfig.expectedCount === "number") {
      if (communityConfig.expectedCount === expectedCommunitySkills.length) pass("Community expected count matches inventory", String(communityConfig.expectedCount));
      else fail("Community expected count matches inventory", communityConfig.expectedCount + " != " + expectedCommunitySkills.length);
    }
  } else if (expectedCommunitySkills.length === 0) {
    warn("Community skill expectations not declared", "mode=" + String(communityConfig.mode || "unknown"));
  }
  for (const skill of expectedCommunitySkills) {
    const globalSkillDir = path.join(GLOBAL_SKILLS_DIR, skill);
    const claudeSkillDir = path.join(GLOBAL_CLAUDE_SKILLS_DIR, skill);
    const skillMdPath = path.join(globalSkillDir, "SKILL.md");
    const missing = !(await pathExists(globalSkillDir));
    if (missing && communityConfig.strict) fail("Required community skill installed globally", skill);
    else if (missing) warn("Optional community skill missing globally", skill);
    else pass("Community skill installed globally", skill);

    if (!missing) {
      if (await pathExists(skillMdPath)) pass("Community skill has SKILL.md", skill);
      else if (communityConfig.strict) fail("Community skill has SKILL.md", skill);
      else warn("Community skill has SKILL.md", skill);

      if (opencodePaths.includes(normalizedGlobal) && await pathExists(skillMdPath)) pass("OpenCode can resolve community skill", skill);
      else if (communityConfig.strict) fail("OpenCode can resolve community skill", skill);
      else warn("OpenCode can resolve community skill", skill);

      if (await pathExists(claudeSkillDir)) pass("Claude slash skill installed for community skill", skill);
      else if (communityConfig.strict) fail("Claude slash skill installed for community skill", skill);
      else warn("Claude slash skill installed for community skill", skill);
    }
  }

  for (const skill of localSkills) {
    if (await pathExists(path.join(GLOBAL_SKILLS_DIR, skill))) pass("Global copy exists for local skill", skill);
    else fail("Global copy exists for local skill", skill);
    if (await pathExists(path.join(GLOBAL_CLAUDE_SKILLS_DIR, skill))) pass("Claude slash skill installed for local skill", skill);
    else fail("Claude slash skill installed for local skill", skill);
    if (opencodePaths.includes(await normalizePath(projectSkillsRoot))) pass("OpenCode can resolve local skill", skill);
    else fail("OpenCode can resolve local skill", skill);
  }

  const failures = checks.filter((check) => !check.ok);
  for (const check of checks) {
    const prefix = check.ok ? (check.level || "PASS") : "FAIL";
    console.log(prefix + " " + check.label + (check.detail ? ": " + check.detail : ""));
  }

  if (failures.length) {
    console.error("\nHarness verification failed with " + failures.length + " issue(s).");
    process.exitCode = 1;
    return;
  }

  console.log("\nHarness verification passed.");
};

run().catch((e) => { console.error("Harness verification failed:", e); process.exitCode = 1; });
